### ISSUE TITLE
Job-component.blade.php no abre el modal correctamente.

### ISSUE THREAD

**Issue by ghost** [SonJiren/services#1]
Este error es del archivo **_job-component.blade.php_**, en "**resources/views/livewire**"  en app el cual no abre o funciona correctamente en la aplicación de Laravel.

El modal como tal funciona, pero al momento de borrar un registro no hace nada, a menos de que se abra otro modal funcional, como crear otro registro o editar, en dicho caso, el modal de borrar se abrirá correctamente.

Este error es de la rama "**main**", aún no se hace un git merge o pull entre main y la mía.

**Comment by JoseEmiliano01** [comment]
que pro xdxdxdxdxdxxdxdxdxxxdxddxdxxd

**Comment by SonJiren** [comment]
completado inesperadamente xd ,todo un dia solo para un /div xd
